/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { DecimalERC20, DecimalERC20Interface } from "../DecimalERC20";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class DecimalERC20__factory {
  static readonly abi = _abi;
  static createInterface(): DecimalERC20Interface {
    return new utils.Interface(_abi) as DecimalERC20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DecimalERC20 {
    return new Contract(address, _abi, signerOrProvider) as DecimalERC20;
  }
}
