/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IFuturePriceFeed,
  IFuturePriceFeedInterface,
} from "../IFuturePriceFeed";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
    ],
    name: "getPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IFuturePriceFeed__factory {
  static readonly abi = _abi;
  static createInterface(): IFuturePriceFeedInterface {
    return new utils.Interface(_abi) as IFuturePriceFeedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFuturePriceFeed {
    return new Contract(address, _abi, signerOrProvider) as IFuturePriceFeed;
  }
}
