/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ISwapForFuture,
  ISwapForFutureInterface,
} from "../ISwapForFuture";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "reserveToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
    ],
    name: "settleFutureProfit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenIn",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenOut",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountOutMin",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "swapIn",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ISwapForFuture__factory {
  static readonly abi = _abi;
  static createInterface(): ISwapForFutureInterface {
    return new utils.Interface(_abi) as ISwapForFutureInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISwapForFuture {
    return new Contract(address, _abi, signerOrProvider) as ISwapForFuture;
  }
}
