/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITradeStake, ITradeStakeInterface } from "../ITradeStake";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_score",
        type: "uint256",
      },
    ],
    name: "updateScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITradeStake__factory {
  static readonly abi = _abi;
  static createInterface(): ITradeStakeInterface {
    return new utils.Interface(_abi) as ITradeStakeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITradeStake {
    return new Contract(address, _abi, signerOrProvider) as ITradeStake;
  }
}
