/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { PropertyERC20, PropertyERC20Interface } from "../PropertyERC20";

const _abi = [
  {
    inputs: [],
    name: "decimals",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class PropertyERC20__factory {
  static readonly abi = _abi;
  static createInterface(): PropertyERC20Interface {
    return new utils.Interface(_abi) as PropertyERC20Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PropertyERC20 {
    return new Contract(address, _abi, signerOrProvider) as PropertyERC20;
  }
}
